### ISSUE TITLE
Install instructions.

### ISSUE THREAD

**Issue by LostKobrakai** [almightycouch/gitgud#15]
It would be nice to have a document outline how to run the gitgud from an initial git clone. 

These are the steps I took to get phoenix running, but I'm not sure how I would create an account for the web interface.

```
- clone
- (install libgit2)
- mix ecto.create
- change git/ssh-key directory in apps/gitgud/config/config.exs
- generate ssh-key
- mix phx.server
```

**Comment by redrabbit** [comment]
Hi @LostKobrakai,

It's true that the README is kind of minimalistic. It has already two sections providing steps to install libgit2 and setup ssh-key related things. It could have a brief introduction on Ecto setup thought.

The project is in a alpha stage, there is not much to do once Phoenix is started. You can only browse user repos and browse code.

You have to manage user and repos through an IEX. I kind of assume that people interacting with it this early have sufficient knowledge to get things started.

Anyway, we could definitely improve the README.

**Comment by Exadra37** [comment]
If you gonna assume that others have the same knowledge as you to give a try to this project then you are just throwing out many potential users to get in love by your project, plus  possible contributors.

The success of any projects start in good documentation from the very begin ;)

Also a working demo can make miracles regarding earlier adoption and enthusiasm.

You can get support from cloud providers for a open source project like this to be initially hosted for free.

A colleague of work have applied with a very dummy app to [this AWS](https://aws.amazon.com/activate/) program and got a sponsorship from them.

I can help with the Docker stack to run this for development and for the demo :)

**Comment by redrabbit** [comment]
@Exadra37, @LostKobrakai, I'm aware on the importance of providing basic support for more novice users. There's few things I want to do in order to facilitate early adoption for new-comers:

* Better documentation.
* Easy to understand, step-by-step Installation guide in README.md.
* More understandable error and warning messages.

I've planned to get this done during next week but can use any kind of help (advices or PRs).
