### ISSUE TITLE
Add RegistrationController allowing people to signup.

### ISSUE THREAD

**Issue by redrabbit** [almightycouch/gitgud#18]
Currently, there is no possibility to signup. Users have to be created from an IEx session.

**Comment by OvermindDL1** [comment]
Or rather identify providers should be set up, for example I'll need to use OpenIDConnect/OAuth2.

**Comment by redrabbit** [comment]
@OvermindDL1, thanks for the suggestion. Two-phase authentication is on the roadmap ([Überauth](https://github.com/ueberauth/ueberauth)).

I try to get a usable and polished version 0.2.0 out soon, OAuth2 support will come later.
