### ISSUE TITLE
Is this related to gitgud.io

### ISSUE THREAD

**Issue by DonaldTsang** [almightycouch/gitgud#50]
If not the name clash would cause some issues

**Comment by redrabbit** [comment]
This project is not related to [gitgud.io](https://gitgud.io) which is an hosting platform running [GitLab](https://gitlab.com).

I'm aware of the name clash but don't see any real issues here. It's basically a cheap word-play that inspired many projects related to Git.

> Git Gud: A intentionally misspelled phrase meaning "get good." Generally used to pock fun at and mock inexperienced players in a particular video game.
> [Urban Dictionary](https://www.urbandictionary.com/define.php?term=GiT%20GuD)


Technically, *gitgud*  is one of the umbrella application (`apps/gitgud`) and stands in contrast with *gitrekt* (`apps/gitrekt`). An other video game inspired [world-play](https://www.urbandictionary.com/define.php?term=git%20rekt).

I do own [git.limo](https://git.limo) where I plan to launch the platform once it's getting more stable. On GitHub, the project's repository might be renamed to `git-limo` or `git.limo` in future. I can also imagine that the project will be self-hosted on [git.limo](https://git.limo) and the GitHub repository will be archived or deleted.

**Comment by DonaldTsang** [comment]
@redrabbit I understand the wordplay, rather having two divergent products with the same name is a bit uncomfortable. Good to know that Git-Limo is running.
