### ISSUE TITLE
Failed to load NIF library: geef_nif.so: undefined symbol:

### ISSUE THREAD

**Issue by CharlotteDunois** [almightycouch/gitgud#65]
Trying to compile gitgud will lead to the following error:

Debian (Docker (elixir-1.9.1 image) and Jessie (no Docker)):
```
23:28:53.168 [error] Process #PID<0.6967.0> raised an exception
** (RuntimeError) got 'Failed to load NIF library: \'/gitgud/_build/dev/lib/gitrekt/priv/geef_nif.so:                                undefined symbol: git_diff_to_buf\'' while retrieving Exception.message/1 for %RuntimeError{mes                               sage: 'Failed to load NIF library: \'/gitgud/_build/dev/lib/gitrekt/priv/geef_nif.so: undefined symbo                               l: git_diff_to_buf\''} (expected a string)
    lib/gitrekt/git.ex:120: GitRekt.Git.load_nif/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
```

Ubuntu (Docker (built from 18.04 image)):
```
23:28:53.168 [error] Process #PID<0.6967.0> raised an exception
** (RuntimeError) got 'Failed to load NIF library: \'/gitgud/_build/dev/lib/gitrekt/priv/geef_nif.so:                                undefined symbol: git_commit_committer\'' while retrieving Exception.message/1 for %RuntimeError{mes                               sage: 'Failed to load NIF library: \'/gitgud/_build/dev/lib/gitrekt/priv/geef_nif.so: undefined symbo                               l: git_commit_committer\''} (expected a string)
    lib/gitrekt/git.ex:120: GitRekt.Git.load_nif/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
```

Both use the same erlang + elixir version:
```
Erlang/OTP 22 [erts-10.5.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 20)
```

On Ubuntu the following libgit2-dev version is installed: v0.26.0
On Debian the following libgit2-dev version is installed: v0.25.1

This error seems to be (loosely) related to #61. However adding `-Wl,--no-as-needed` to gitrekt makefile does not resolve the issue for me.

I am opening this issue ticket here, because you maintainers know certainly more about geef than me. If this is a bug in geef, please open an issue on the related issue tracker.

**Comment by CharlotteDunois** [comment]
Here's the complete log of the debian docker container.
[buildlog.txt](https://github.com/almightycouch/gitgud/files/3689711/buildlog.txt)

**Comment by redrabbit** [comment]
> This error seems to be (loosely) related to #61. However adding `-Wl,--no-as-needed` to gitrekt makefile does not resolve the issue for me.

From your output logs, this seems very related to #61. Can you run`ldd` on `geef_nif.so` (see [comment](https://github.com/almightycouch/gitgud/issues/61#issuecomment-532236053)) and paste the results here?

Did you modify the `LD_FLAGS` variable in `Makefile` as indicated [here](https://github.com/almightycouch/gitgud/issues/61#issuecomment-532238991)? Could you run `make clean && make` in `apps/gitrekt` and past the output here?

**Comment by CharlotteDunois** [comment]
@redrabbit 
> From your output logs, this seems very related to #61. Can you run`ldd` on `geef_nif.so` (see [comment](https://github.com/almightycouch/gitgud/issues/61#issuecomment-532236053)) and paste the results here?

[ldd.txt](https://github.com/almightycouch/gitgud/files/3697218/ldd.txt)

> Did you modify the `LD_FLAGS` variable in `Makefile` as indicated [here](https://github.com/almightycouch/gitgud/issues/61#issuecomment-532238991)? Could you run `make clean && make` in `apps/gitrekt` and past the output here?

[make.txt](https://github.com/almightycouch/gitgud/files/3697185/make.txt)

After make, recompiling using `mix compile --force` does not change the error or output.

**Comment by redrabbit** [comment]
I've just tried with a fresh Ubuntu 19.04 and did not get any trouble compiling and running the server. I'll check with 18.04 asap.

Could you maybe try with Ubuntu 19.04. I don't really understand how we can get different results using Docker containers.

How did you install Elixir and Erlang? You are running 1.9.1 which is quite new. With the standard Ubuntu package repositories, I've got version 1.7.4 installed.

**Comment by CharlotteDunois** [comment]
You are right, on 19.04 it works - but only with the changes to gitrekt's `Makefile`. `libgit2-dev` is 0.27.7 on 19.04 - I'll try to see if I can manually compile a newer version of libgit2 on 18.04 and test if it's related to the version.

**Comment by CharlotteDunois** [comment]
Update: I installed in the debian container `libgit2-dev` 0.27.4 from `stretch-backports` - with the backport I can successfully compile the application.

**Comment by redrabbit** [comment]
@CharlotteDunois did you have to update the `Makefile` as well with Debian or did it work out of the box?

**Comment by CharlotteDunois** [comment]
@redrabbit I can confirm that it works out of the box with `0.27.4`.
