### ISSUE TITLE
How to properly install Web

### ISSUE THREAD

**Issue by tiotolstoy** [almightycouch/gitgud#66]
I got the app backend running fine, but the web UI is not there at all. Currently all HTML.

So far I have tried to `cd assets/` and `npm install` 

How do I install the UI?

**Comment by redrabbit** [comment]
What do you mean by `Currently all HTML`? Does the server render the page?  Is the stylesheet missing/not loading? Any error/warning logs at compile time?

Normally, `npm install` in `apps/gitgud_web/assets` should be sufficient to setup the NPM dependencies. Running `mix phx.server` should compile them correctly.

**Comment by redrabbit** [comment]
@tiotolstoy, I've fixed a few things related to the asset pipeline. Maybe you could pull from master and see if your issue is fixed.

**Comment by skwerlman** [comment]
running mix phx.server without first running npm install results in an error message rather than doing that for you:
```
[error] Could not start node watcher because script "/mnt/code/gitgud/apps/gitgud_web/assets/node_modules/webpack/bin/webpack.js" does not exist. Your Phoenix application is still running, however assets won't be compiled. You may fix this by running "cd assets && npm install".
```
after running npm install manually it works fine

**Comment by redrabbit** [comment]
I've enhanced the installation procedure in `README.md`. Fixing a few things and adding an extra step for installing NPM dependencies.
