### ISSUE TITLE
npm install requires password

### ISSUE THREAD

**Issue by spacebat** [almightycouch/gitgud#84]
Following the instructions in the readme, I get up to this line which I run inside the gitgud project root, but get the following error:

$ npm install --prefix apps/gitgud_web/assets
npm ERR! code E401
npm ERR! Incorrect or missing password.
...

I don't have an npm account - is this necessary?

**Comment by redrabbit** [comment]
A wild guess. I had something similar not so long ago:

https://github.com/almightycouch/gitgud/blob/1303aa5f8ade9683630c310c7fd96d12f407ca5d/apps/gitgud_web/assets/package-lock.json#L39

I think the `@fontawesome` repository (which provides a free and a paid version) gets locked-up from time to time.

**Comment by spacebat** [comment]
@redrabbit thanks, that makes sense. It's still happening, so I'll try it again tomorrow.
